name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! 🚀
        
        Please search existing issues to avoid duplicates.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - UI/UX Enhancement
        - New Functionality
        - Performance Improvement
        - Developer Experience
        - Security Enhancement
        - Accessibility
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Currently, users cannot..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this problem solved?
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Describe how users would interact with this feature
      placeholder: |
        - As a user, I want to...
        - So that I can...

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: "Alternatively, we could..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for adoption
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples

  - type: checkboxes
    id: considerations
    attributes:
      label: Implementation Considerations
      description: Please check any that apply
      options:
        - label: This feature should work on all websites
        - label: This feature needs Chrome permissions
        - label: This feature affects performance
        - label: This feature needs user data storage
        - label: This feature needs external API integration

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have provided a clear problem statement
          required: true
        - label: I understand this is a volunteer project
          required: true